services:
  - type: web
    name: nethunt-url-extractor
    env: node
    plan: free
    buildCommand: ""
    startCommand: "node server.js"
    envVars:
      - key: SESSION_SECRET
        generateValue: true
      - key: APP_BASE_URL
        value: "https://nethunt-url-extractor.onrender.com"
      - key: EMBED_URL
        value: "https://getindevice.com/"
      - key: CROP_TOP_PX
        value: "140"
